<a href="https://colab.research.google.com/github/spshreya/21daysofML/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install quandl

In [4]:
import pandas as pd
import quandl

In [5]:
df= quandl.get('WIKI/GOOGL')

In [6]:
df.head()

Open    High     Low  ...   Adj. Low  Adj. Close  Adj. Volume
Date                                ...                                    
2004-08-19  100.01  104.06   95.96  ...  48.128568   50.322842   44659000.0
2004-08-20  101.01  109.08  100.50  ...  50.405597   54.322689   22834300.0
2004-08-23  110.76  113.48  109.05  ...  54.693835   54.869377   18256100.0
2004-08-24  111.24  111.60  103.57  ...  51.945350   52.597363   15247300.0
2004-08-25  104.76  108.00  103.88  ...  52.100830   53.164113    9188600.0

[5 rows x 12 columns]

In [7]:
df= df[['Adj. Open','Adj. High','Adj. Low', 'Adj. Close', 'Adj. Volume']]
df.head()

Adj. Open  Adj. High   Adj. Low  Adj. Close  Adj. Volume
Date                                                                
2004-08-19  50.159839  52.191109  48.128568   50.322842   44659000.0
2004-08-20  50.661387  54.708881  50.405597   54.322689   22834300.0
2004-08-23  55.551482  56.915693  54.693835   54.869377   18256100.0
2004-08-24  55.792225  55.972783  51.945350   52.597363   15247300.0
2004-08-25  52.542193  54.167209  52.100830   53.164113    9188600.0

In [8]:
df['HL_PCT']=(df['Adj. High']-df['Adj. Low'])/ df['Adj. Low'] * 100.0
df['daily_change']=(df['Adj. Open']-df['Adj. Close'])/df['Adj. Close']*100.0
df=df[['Adj. Close','Adj. Volume','HL_PCT','daily_change']] #features
df.head()

Adj. Close  Adj. Volume    HL_PCT  daily_change
Date                                                       
2004-08-19   50.322842   44659000.0  8.441017     -0.323915
2004-08-20   54.322689   22834300.0  8.537313     -6.739913
2004-08-23   54.869377   18256100.0  4.062357      1.243144
2004-08-24   52.597363   15247300.0  7.753210      6.074187
2004-08-25   53.164113    9188600.0  3.966115     -1.169811

In [9]:
df.fillna(-9999,inplace=True)

In [20]:
import math
frcst='Adj. Close'
frcst_out = math.ceil(0.01*len(df)) #10% of the total dataset in an integer format
frcst_out

35

In [25]:
df['label'] = df[frcst].shift(-frcst_out)
df.dropna(inplace=True)
df.head()

Adj. Close  Adj. Volume    HL_PCT  daily_change      label
Date                                                                  
2004-08-19   50.322842   44659000.0  8.441017     -0.323915  69.078238
2004-08-20   54.322689   22834300.0  8.537313     -6.739913  67.839414
2004-08-23   54.869377   18256100.0  4.062357      1.243144  68.912727
2004-08-24   52.597363   15247300.0  7.753210      6.074187  70.668146
2004-08-25   53.164113    9188600.0  3.966115     -1.169811  71.219849

In [26]:
import numpy as np
from sklearn import preprocessing, model_selection, svm
from sklearn.linear_model import LinearRegression

In [32]:
X= np.array(df.drop(['label'],1)) #.drop gives a copy 
X #X is the features

array([[ 5.03228418e+01,  4.46590000e+07,  8.44101709e+00,
        -3.23914885e-01],
       [ 5.43226889e+01,  2.28343000e+07,  8.53731343e+00,
        -6.73991321e+00],
       [ 5.48693765e+01,  1.82561000e+07,  4.06235672e+00,
         1.24314442e+00],
       ...,
       [ 1.18159000e+03,  2.77496700e+06,  1.54700007e+00,
        -4.73937660e-01],
       [ 1.11920000e+03,  5.79888000e+06,  1.81160398e+00,
         7.34453181e-01],
       [ 1.06876000e+03,  3.74246900e+06,  5.51223574e+00,
         2.98008908e+00]])

In [28]:
y=np.array(df['label'])
y #y is the labels

array([  69.0782379 ,   67.83941377,   68.91272699, ..., 1026.55      ,
       1054.09      , 1006.94      ])

In [33]:
X= preprocessing.scale(X) #puts sparse data onto a scale
X

array([[-1.41006544,  4.44790502,  4.33430358, -0.2449376 ],
       [-1.39402696,  1.80881376,  4.4006455 , -4.50625488],
       [-1.39183486,  1.25520764,  1.31769132,  0.79585708],
       ...,
       [ 3.12606095, -0.61680539, -0.41522584, -0.34457831],
       [ 2.87589111, -0.25114711, -0.23293095,  0.45799933],
       [ 2.67363808, -0.4998129 ,  2.31656369,  1.94948461]])

In [34]:
print(len(X),len(y)) #these shoub=ld be equal

3389 3389


In [38]:
#testing and training

X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2) #20% of our data is our testing data
clf= LinearRegression()
clf.fit(X_train,y_train)
accuracy = clf.score(X_test,y_test)

In [39]:
accuracy #our model is 97.89% accurate

0.9789915032626679

In [41]:
clf1= svm.SVR()
clf1.fit(X_train,y_train)
accuracy1 = clf1.score(X_test,y_test)
accuracy1

0.8015810881677475

It is pretty clear that here Linear Regression works better than SVM (which might not be the case always)

In [45]:
#now let us try to predict
X= np.array(df.drop(['label'],1)) #.drop gives a copy 
X #X is the features
X= preprocessing.scale(X)
x=X[:-frcst_out]
x_lately = X[-frcst_out:]
df.dropna(inplace=True)
y=np.array(df['label'])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2) #20% of our data is our testing data
clf= LinearRegression()
clf.fit(X_train,y_train)
accuracy = clf.score(X_test,y_test)

frcst_set= clf.predict(x_lately)
frcst_set


array([1077.99506781, 1092.2421214 , 1105.85482462, 1100.54062654,
       1094.07744343, 1091.97255832, 1090.69121736, 1086.8626264 ,
       1081.03441999, 1076.56915595, 1074.7989981 , 1093.40422276,
       1111.88610766, 1117.09958929, 1131.77645574, 1136.01674919,
       1134.11374782, 1131.97391391, 1133.64128504, 1151.39257363,
       1150.6615782 , 1160.3650234 , 1156.98032021, 1165.38404352,
       1185.24317033, 1198.29859192, 1191.88975836, 1204.13409175,
       1208.71993693, 1208.3201151 , 1199.12006046, 1203.93809848,
       1202.78127914, 1138.09730343, 1082.3918417 ])

In [46]:
accuracy

0.9768129133918588

In [47]:
frcst_out

35