<a href="https://colab.research.google.com/github/spshreya/21daysofML/blob/main/revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY REVISION

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.array([0, 0.5, 1, 1.5, 2])
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int64')

In [5]:
a = np.array([1,2,3,4], dtype='int8')
a.dtype

dtype('int8')

In [6]:
a[0], a[1]

(1, 2)

In [7]:
b[0], b[2], b[-1]  

(0.0, 1.0, 2.0)

In [8]:
b[[0,2,-1]] #multi indexing which can not be found in lists but np arrays


array([0., 1., 2.])

In [9]:
a[1:]

array([2, 3, 4], dtype=int8)

In [10]:
a[1:-1]

array([2, 3], dtype=int8)

In [11]:
a[::2]   #[x::y] prints yth element from the list starting from x

array([1, 3], dtype=int8)

In [12]:
#multidimensional array
aa = np.array([
               [1,2,3],
               [4,5,6]
], dtype='int8')
aa.dtype

dtype('int8')

In [13]:
print('shape =',aa.shape)
print('dimensions=', aa.ndim)
print('size=', aa.size)

shape = (2, 3)
dimensions= 2
size= 6


In [14]:
#a dimension further
bb = np.array([
               [
                [1,2,3],
                [4,5,6]
               ],
               [
                [6,7,8],
                [9,10,11]
               ]
], dtype='float64')
bb

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [15]:
print('shape =',bb.shape)
print('dimensions=', bb.ndim)
print('size=', bb.size)

shape = (2, 2, 3)
dimensions= 3
size= 12


In [16]:
#in case of mismatched rows - notice the difference
c = np.array([
              [
               [1,2,3],
               [4,5,6]
              ],
              [
               [7,8,9]
              ]
])
c.dtype

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


dtype('O')

In [17]:
print('shape =',c.shape)
print('dimensions=', c.ndim)
print('size=', c.size)

shape = (2,)
dimensions= 1
size= 2


In [18]:
#slicing nad indexing square matrix
a= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [19]:
a[1][0]

4

In [20]:
#or 
a[1, 0]

4

In [21]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a[:, :2]    #a[d1, d2, d3, d4]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [23]:
a[1] = np.array([2,2,2])
a

array([[1, 2, 3],
       [2, 2, 2],
       [7, 8, 9]])

In [24]:
#or we can just leave it to numpy
a[2]= 10
a

array([[ 1,  2,  3],
       [ 2,  2,  2],
       [10, 10, 10]])

In [26]:
# STATS

a = np.array([1,2,3,4], dtype='int8')

In [29]:
print(a.max(), a.min(), a.sum(), a.mean(), a.std(), a.var())

4 1 10 2.5 1.118033988749895 1.25
