<a href="https://colab.research.google.com/github/spshreya/21daysofML/blob/main/revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY REVISION

In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3,4])
b = np.array([0, 0.5, 1, 1.5, 2])
type(a)

numpy.ndarray

In [10]:
a.dtype

dtype('int64')

In [13]:
a = np.array([1,2,3,4], dtype='int8')
a.dtype

dtype('int8')

In [3]:
a[0], a[1]

(1, 2)

In [4]:
b[0], b[2], b[-1]  

(0.0, 1.0, 2.0)

In [8]:
b[[0,2,-1]] #multi indexing which can not be found in lists but np arrays


array([0., 1., 2.])

In [5]:
a[1:]

array([2, 3, 4])

In [6]:
a[1:-1]

array([2, 3])

In [7]:
a[::2]   #[x::y] prints yth element from the list starting from x

array([1, 3])

In [17]:
#multidimensional array
aa = np.array([
               [1,2,3],
               [4,5,6]
], dtype='int8')
aa.dtype

dtype('int8')

In [23]:
print('shape =',aa.shape)
print('dimensions=', aa.ndim)
print('size=', aa.size)

shape = (2, 3)
dimensions= 2
size= 6


In [27]:
#a dimension further
bb = np.array([
               [
                [1,2,3],
                [4,5,6]
               ],
               [
                [6,7,8],
                [9,10,11]
               ]
], dtype='float64')
bb

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [28]:
print('shape =',bb.shape)
print('dimensions=', bb.ndim)
print('size=', bb.size)

shape = (2, 2, 3)
dimensions= 3
size= 12


In [29]:
#in case of mismatched rows - notice the difference
c = np.array([
              [
               [1,2,3],
               [4,5,6]
              ],
              [
               [7,8,9]
              ]
])
c.dtype

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


dtype('O')

In [30]:
print('shape =',c.shape)
print('dimensions=', c.ndim)
print('size=', c.size)

shape = (2,)
dimensions= 1
size= 2


In [32]:
#slicing nad indexing square matrix
a= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])